### PR TITLE
Add caveats for unexpanded globs

### PR DESCRIPTION
**Pull request by jan4843**

### CODE REVIEW

**Comment by dylanaraps** [comment]
Another alternative is to add a test `[ -f "$file" ] &&`.

**Comment by jan4843** [comment]
I think so, although `-e` would be more appropriate?

**Comment by dylanaraps** [comment]
Yeah, was just an example. :+1:

**Comment by jan4843** [comment]
Actually `-e` doesn't work if `$file` is a broken symlink. `[[ -e "$file" || -L "$file" ]] &&` should be correct.

**Comment by dylanaraps** [comment]
LGTM :+1:

**Pull request merged**
